name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI devops 2025"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key for remote server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_takima
          chmod 600 ~/.ssh/id_rsa_takima
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventories/setup.yml playbook.yml
